
language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - composer self-update

install:
  - composer install

script:
  - bin/dev-phpunit
